### ISSUE TITLE
Errors when running demo setup

### ISSUE THREAD

**Issue by StFS** [openimis/openimis-dist_dkr#1]
Hi there.

Came across this pretty awesome project by a lucky search.

I wanted to run your demo so I followed the instructions in this module but stumbled across two problems.

First was that I was getting an error when running the backend compose command:
`CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False`

This was an easy fix as I found this:
https://stackoverflow.com/questions/24857158/commanderror-you-must-set-settings-allowed-hosts-if-debug-is-false

So I changed `ALLOWED_HOSTS` to `['*']` and re-built the backend docker image and got past the CommandError.

However, now I get the following error when I try to run `docker-compose up backend`

```
backend_1  | Failed to load core configuration, using default!
backend_1  | ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'core_ModuleConfiguration'. (208) (SQLExecDirectW)")
backend_1  | SystemCheckError: System check identified some issues:
backend_1  | 
backend_1  | ERRORS:
backend_1  | auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
backend_1  | auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
backend_1  | core.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
backend_1  | core.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
backend_1  | Failed to load core configuration, using default!
backend_1  | ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'core_ModuleConfiguration'. (208) (SQLExecDirectW)")
backend_1  | Failed to load core configuration, using default!
backend_1  | ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'core_ModuleConfiguration'. (208) (SQLExecDirectW)")
backend_1  | Performing system checks...
backend_1  | 
backend_1  | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feeedd6e510>
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
backend_1  |     fn(*args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
backend_1  |     self.check(display_num_errors=True)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 425, in check
backend_1  |     raise SystemCheckError(msg)
backend_1  | django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
backend_1  | 
backend_1  | ERRORS:
backend_1  | auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
backend_1  | auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
backend_1  | core.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
backend_1  | core.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
backend_1  | 	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
backend_1  | 
backend_1  | System check identified 4 issues (0 silenced).
```
I'd appreciate any help if you know what's going on with this and how I can fix it.

**Comment by xgill** [comment]
Hi StFS,
Thank you for reaching out with the issues you encountered.
- about DEBUG/ALLOWED_HOSTS, we (temporary) switched back to enforced DEBUG: it solve problem you were facing... and we still need to fix the static files problem (when deployed behind a gateway) before switching DEBUG off again.
- the 'Failed to load core configuration, using default!' is just a warning: it says that the database doesn't contain the configuration for the core module (cfr. core_ModuleConfiguration), so it takes the default values. At the moment, it only concerns the used calendar and it defaults to Gregorian calendar.
- the 'User.groups' problem comes from a too-early and incompatible publish of the openimis-core (v0.0.4) from us in pypi yesterday. Sorry for that. We now aligned all projects masters to the same level. May I ask you to give our project another chance by updating your local repos? Warning: as described in the README, there is now a (nginx) gateway in front of the the backend, so, beside updating your local repos, you'll also need to clone the gateway (cfr. https://github.com/openimis/openimis-gateway_dkr)

Hope these elements will help you to get started... and don't hesitate to share any issue or possible improvement with us...
Thanks again,
Xavier

**Comment by xgill** [comment]
Issue has been confirmed closed.
